### ISSUE TITLE
Movies APIs

### ISSUE THREAD

**Issue by alienalien13** [illWatchers/ill-watch#2]
Research and investigation.
APIs endpoints and apis.

**Comment by flashlee** [comment]
So far that's what I found. I'll make more detailed investigation later.
https://www.themoviedb.org/documentation/api
http://www.omdbapi.com/
we can make our own custom api (https://stackoverflow.com/questions/1966503/does-imdb-provide-an-api)
looks like themoviedb has pretty solid api
