### ISSUE TITLE
Firebase setup

### ISSUE THREAD

**Issue by alienalien13** [illWatchers/ill-watch#4]
- [x] Create firebase project
- [x] Create DB
- [x] Configure auth to firebase

**Comment by flashlee** [comment]
I saw that we already have 2 DBs created if firebase. I assume we want to use Cloud Firestore. You can read comparison [here](https://firebase.google.com/docs/database/rtdb-vs-firestore)
@maybelinot @alienalien13  are you ok if I delete realtime database?

**Comment by flashlee** [comment]
@alienalien13 @maybelinot I enabled email/password authentication and added 1 test user. 
So we can close this issue.

**Comment by maybelinot** [comment]
@flashlee Why do we need email/password auth?

**Comment by flashlee** [comment]
@maybelinot I enabled it for feature. As I remember for MVP we agreed not to implement user auth.
@alienalien13 ?

**Comment by flashlee** [comment]
Anyway it can be changed to other method at any time
